# Generated by Django 4.1.3 on 2022-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_alter_memory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content1", models.TextField(max_length=7)),
                ("content2", models.TextField(max_length=7)),
                ("content3", models.TextField(max_length=7)),
                ("content4", models.TextField(max_length=7)),
                ("content5", models.TextField(max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
