# Generated by Django 4.1.3 on 2022-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_keywordpost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keywordpost",
            old_name="created_at",
            new_name="create_dat",
        ),
        migrations.RenameField(
            model_name="keywordpost",
            old_name="updated_at",
            new_name="update_dat",
        ),
        migrations.RemoveField(
            model_name="keywordpost",
            name="content4",
        ),
        migrations.RemoveField(
            model_name="keywordpost",
            name="content5",
        ),
        migrations.RemoveField(
            model_name="keywordpost",
            name="title",
        ),
        migrations.AddField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[("Ct", "만화"), ("Od", "유화"), ("Sc", "스케치")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="keywordpost",
            name="Weather",
            field=models.CharField(
                choices=[("Sn", "눈이 와요"), ("R", "비가 와요"), ("S", "맑아요"), ("C", "흐려요")],
                max_length=10,
                null=True,
            ),
        ),
    ]
